[[main]]
  identifier = "en-ai"
  name = "AI"
  url = "/en/ai/"
  weight = 10

[[main]]
  identifier = "en-tech"
  name = "Technology"
  url = "/en/tech/"
  weight = 20

[[main]]
  identifier = "en-research"
  name = "Research"
  url = "/en/research/"
  weight = 30

[[main]]
  identifier = "en-tags"
  name = "Tags"
  url = "/en/tags/"
  weight = 40

[[main]]
  identifier = "en-about"
  name = "About"
  url = "/en/about/"
  weight = 50
